# Generated by Django 5.1.4 on 2025-04-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestureVideo',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('gesture', models.CharField(max_length=100)),
                ('gesture_type', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='gesture_videos/')),
            ],
        ),
    ]
