# Generated by Django 5.1.4 on 2025-04-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islapp', '0002_gesturevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesturevideo',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
