# Generated by Django 5.1.4 on 2025-04-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islapp', '0003_gesturevideo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesturevideo',
            name='gesture_type',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Seasons', 'Seasons')], default='Electronics', max_length=20),
        ),
    ]
